/*
 * CLOUD API
 *
 * An enterprise-grade Infrastructure is provided as a Service (IaaS) solution that can be managed through a browser-based \"Data Center Designer\" (DCD) tool or via an easy to use API.   The API allows you to perform a variety of management tasks such as spinning up additional servers, adding volumes, adjusting networking, and so forth. It is designed to allow users to leverage the same power and flexibility found within the DCD visual tool. Both tools are consistent with their concepts and lend well to making the experience smooth and intuitive.
 *
 * API version: 5.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ImageProperties struct {
	// A name of that resource
	Name string `json:"name,omitempty"`
	// Human readable description
	Description string `json:"description,omitempty"`
	// Location of that image/snapshot. 
	Location string `json:"location,omitempty"`
	// The size of the image in GB
	Size float64 `json:"size,omitempty"`
	// Is capable of CPU hot plug (no reboot required)
	CpuHotPlug bool `json:"cpuHotPlug,omitempty"`
	// Is capable of CPU hot unplug (no reboot required)
	CpuHotUnplug bool `json:"cpuHotUnplug,omitempty"`
	// Is capable of memory hot plug (no reboot required)
	RamHotPlug bool `json:"ramHotPlug,omitempty"`
	// Is capable of memory hot unplug (no reboot required)
	RamHotUnplug bool `json:"ramHotUnplug,omitempty"`
	// Is capable of nic hot plug (no reboot required)
	NicHotPlug bool `json:"nicHotPlug,omitempty"`
	// Is capable of nic hot unplug (no reboot required)
	NicHotUnplug bool `json:"nicHotUnplug,omitempty"`
	// Is capable of Virt-IO drive hot plug (no reboot required)
	DiscVirtioHotPlug bool `json:"discVirtioHotPlug,omitempty"`
	// Is capable of Virt-IO drive hot unplug (no reboot required). This works only for non-Windows virtual Machines.
	DiscVirtioHotUnplug bool `json:"discVirtioHotUnplug,omitempty"`
	// Is capable of SCSI drive hot plug (no reboot required)
	DiscScsiHotPlug bool `json:"discScsiHotPlug,omitempty"`
	// Is capable of SCSI drive hot unplug (no reboot required). This works only for non-Windows virtual Machines.
	DiscScsiHotUnplug bool `json:"discScsiHotUnplug,omitempty"`
	// OS type of this Image
	LicenceType string `json:"licenceType"`
	// This indicates the type of image
	ImageType string `json:"imageType,omitempty"`
	// Indicates if the image is part of the public repository or not
	Public bool `json:"public,omitempty"`
}
