/*
 * CLOUD API
 *
 * An enterprise-grade Infrastructure is provided as a Service (IaaS) solution that can be managed through a browser-based \"Data Center Designer\" (DCD) tool or via an easy to use API.   The API allows you to perform a variety of management tasks such as spinning up additional servers, adding volumes, adjusting networking, and so forth. It is designed to allow users to leverage the same power and flexibility found within the DCD visual tool. Both tools are consistent with their concepts and lend well to making the experience smooth and intuitive.
 *
 * API version: 5.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ResourceLimits struct {
	// maximum number of cores per server
	CoresPerServer int32 `json:"coresPerServer"`
	// maximum cores per contract
	CoresPerContract int32 `json:"coresPerContract"`
	// number of cores provisioned
	CoresProvisioned int32 `json:"coresProvisioned"`
	// maximum ram per server
	RamPerServer int32 `json:"ramPerServer"`
	// maximum ram per contract
	RamPerContract int32 `json:"ramPerContract"`
	// ram provisioned
	RamProvisioned int32 `json:"ramProvisioned"`
	// hdd limit per volume
	HddLimitPerVolume int64 `json:"hddLimitPerVolume"`
	// hdd limit per contract
	HddLimitPerContract int64 `json:"hddLimitPerContract"`
	// hdd volume provisioned
	HddVolumeProvisioned int64 `json:"hddVolumeProvisioned"`
	// ssd limit per volume
	SsdLimitPerVolume int64 `json:"ssdLimitPerVolume"`
	// ssd limit per contract
	SsdLimitPerContract int64 `json:"ssdLimitPerContract"`
	// ssd volume provisioned
	SsdVolumeProvisioned int64 `json:"ssdVolumeProvisioned"`
	// total reservable ip limit of the customer
	ReservableIps int32 `json:"reservableIps"`
	// reserved ips on a contract
	ReservedIpsOnContract int32 `json:"reservedIpsOnContract"`
	// reserved ips in use
	ReservedIpsInUse int32 `json:"reservedIpsInUse"`
	// k8s clusters total limit
	K8sClusterLimitTotal int32 `json:"k8sClusterLimitTotal"`
	// k8s clusters provisioned
	K8sClustersProvisioned int32 `json:"k8sClustersProvisioned"`
}
