/*
 * CLOUD API
 *
 * An enterprise-grade Infrastructure is provided as a Service (IaaS) solution that can be managed through a browser-based \"Data Center Designer\" (DCD) tool or via an easy to use API.   The API allows you to perform a variety of management tasks such as spinning up additional servers, adding volumes, adjusting networking, and so forth. It is designed to allow users to leverage the same power and flexibility found within the DCD visual tool. Both tools are consistent with their concepts and lend well to making the experience smooth and intuitive.
 *
 * API version: 5.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Type string

// List of Type
const (
	DATACENTER ModelType = "datacenter"
	SERVER ModelType = "server"
	VOLUME ModelType = "volume"
	NIC ModelType = "nic"
	LOADBALANCER ModelType = "loadbalancer"
	LOCATION ModelType = "location"
	FIREWALL_RULE ModelType = "firewall-rule"
	IMAGE ModelType = "image"
	SNAPSHOT ModelType = "snapshot"
	LAN ModelType = "lan"
	IPBLOCK ModelType = "ipblock"
	PCC ModelType = "pcc"
	CONTRACT ModelType = "contract"
	USER ModelType = "user"
	GROUP ModelType = "group"
	COLLECTION ModelType = "collection"
	RESOURCE ModelType = "resource"
	REQUEST ModelType = "request"
	REQUEST_STATUS ModelType = "request-status"
	S3KEY ModelType = "s3key"
	BACKUPUNIT ModelType = "backupunit"
	LABEL ModelType = "label"
	K8S ModelType = "k8s"
	NODEPOOL ModelType = "nodepool"
)
