/*
 * CLOUD API
 *
 * An enterprise-grade Infrastructure is provided as a Service (IaaS) solution that can be managed through a browser-based \"Data Center Designer\" (DCD) tool or via an easy to use API.   The API allows you to perform a variety of management tasks such as spinning up additional servers, adding volumes, adjusting networking, and so forth. It is designed to allow users to leverage the same power and flexibility found within the DCD visual tool. Both tools are consistent with their concepts and lend well to making the experience smooth and intuitive.
 *
 * API version: 5.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type NoStateMetaData struct {
	// Resource's Entity Tag as defined in http://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.11 . Entity Tag is also added as an 'ETag response header to requests which don't use 'depth' parameter. 
	Etag string `json:"etag,omitempty"`
	// The time the Resource was created
	CreatedDate time.Time `json:"createdDate,omitempty"`
	// The user who has created the resource.
	CreatedBy string `json:"createdBy,omitempty"`
	// The user id of the user who has created the resource.
	CreatedByUserId string `json:"createdByUserId,omitempty"`
	// The last time the resource has been modified
	LastModifiedDate time.Time `json:"lastModifiedDate,omitempty"`
	// The user who last modified the resource.
	LastModifiedBy string `json:"lastModifiedBy,omitempty"`
	// The user id of the user who has last modified the resource.
	LastModifiedByUserId string `json:"lastModifiedByUserId,omitempty"`
}
