/*
 * CLOUD API
 *
 * An enterprise-grade Infrastructure is provided as a Service (IaaS) solution that can be managed through a browser-based \"Data Center Designer\" (DCD) tool or via an easy to use API.   The API allows you to perform a variety of management tasks such as spinning up additional servers, adding volumes, adjusting networking, and so forth. It is designed to allow users to leverage the same power and flexibility found within the DCD visual tool. Both tools are consistent with their concepts and lend well to making the experience smooth and intuitive.
 *
 * API version: 5.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/cloudapi/v5/",
		Index,
	},

	Route{
		"RootGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/",
		RootGet,
	},

	Route{
		"BackupunitsBackupunitIdDelete",
		strings.ToUpper("Delete"),
		"/cloudapi/v5/backupunits/{backupunitId}",
		BackupunitsBackupunitIdDelete,
	},

	Route{
		"BackupunitsBackupunitIdGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/backupunits/{backupunitId}",
		BackupunitsBackupunitIdGet,
	},

	Route{
		"BackupunitsBackupunitIdPatch",
		strings.ToUpper("Patch"),
		"/cloudapi/v5/backupunits/{backupunitId}",
		BackupunitsBackupunitIdPatch,
	},

	Route{
		"BackupunitsBackupunitIdPut",
		strings.ToUpper("Put"),
		"/cloudapi/v5/backupunits/{backupunitId}",
		BackupunitsBackupunitIdPut,
	},

	Route{
		"BackupunitsBackupunitIdSsourlGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/backupunits/{backupunitId}/ssourl",
		BackupunitsBackupunitIdSsourlGet,
	},

	Route{
		"BackupunitsGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/backupunits",
		BackupunitsGet,
	},

	Route{
		"BackupunitsPost",
		strings.ToUpper("Post"),
		"/cloudapi/v5/backupunits",
		BackupunitsPost,
	},

	Route{
		"ContractsGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/contracts",
		ContractsGet,
	},

	Route{
		"DatacentersDatacenterIdDelete",
		strings.ToUpper("Delete"),
		"/cloudapi/v5/datacenters/{datacenterId}",
		DatacentersDatacenterIdDelete,
	},

	Route{
		"DatacentersDatacenterIdGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/datacenters/{datacenterId}",
		DatacentersDatacenterIdGet,
	},

	Route{
		"DatacentersDatacenterIdPatch",
		strings.ToUpper("Patch"),
		"/cloudapi/v5/datacenters/{datacenterId}",
		DatacentersDatacenterIdPatch,
	},

	Route{
		"DatacentersDatacenterIdPut",
		strings.ToUpper("Put"),
		"/cloudapi/v5/datacenters/{datacenterId}",
		DatacentersDatacenterIdPut,
	},

	Route{
		"DatacentersGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/datacenters",
		DatacentersGet,
	},

	Route{
		"DatacentersPost",
		strings.ToUpper("Post"),
		"/cloudapi/v5/datacenters",
		DatacentersPost,
	},

	Route{
		"IpblocksGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/ipblocks",
		IpblocksGet,
	},

	Route{
		"IpblocksIpblockIdDelete",
		strings.ToUpper("Delete"),
		"/cloudapi/v5/ipblocks/{ipblockId}",
		IpblocksIpblockIdDelete,
	},

	Route{
		"IpblocksIpblockIdGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/ipblocks/{ipblockId}",
		IpblocksIpblockIdGet,
	},

	Route{
		"IpblocksIpblockIdPatch",
		strings.ToUpper("Patch"),
		"/cloudapi/v5/ipblocks/{ipblockId}",
		IpblocksIpblockIdPatch,
	},

	Route{
		"IpblocksIpblockIdPut",
		strings.ToUpper("Put"),
		"/cloudapi/v5/ipblocks/{ipblockId}",
		IpblocksIpblockIdPut,
	},

	Route{
		"IpblocksPost",
		strings.ToUpper("Post"),
		"/cloudapi/v5/ipblocks",
		IpblocksPost,
	},

	Route{
		"ImagesGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/images",
		ImagesGet,
	},

	Route{
		"ImagesImageIdDelete",
		strings.ToUpper("Delete"),
		"/cloudapi/v5/images/{imageId}",
		ImagesImageIdDelete,
	},

	Route{
		"ImagesImageIdGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/images/{imageId}",
		ImagesImageIdGet,
	},

	Route{
		"ImagesImageIdPatch",
		strings.ToUpper("Patch"),
		"/cloudapi/v5/images/{imageId}",
		ImagesImageIdPatch,
	},

	Route{
		"ImagesImageIdPut",
		strings.ToUpper("Put"),
		"/cloudapi/v5/images/{imageId}",
		ImagesImageIdPut,
	},

	Route{
		"K8sGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/k8s",
		K8sGet,
	},

	Route{
		"K8sK8sClusterIdDelete",
		strings.ToUpper("Delete"),
		"/cloudapi/v5/k8s/{k8sClusterId}",
		K8sK8sClusterIdDelete,
	},

	Route{
		"K8sK8sClusterIdGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/k8s/{k8sClusterId}",
		K8sK8sClusterIdGet,
	},

	Route{
		"K8sK8sClusterIdKubeconfigGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/k8s/{k8sClusterId}/kubeconfig",
		K8sK8sClusterIdKubeconfigGet,
	},

	Route{
		"K8sK8sClusterIdNodepoolsGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/k8s/{k8sClusterId}/nodepools",
		K8sK8sClusterIdNodepoolsGet,
	},

	Route{
		"K8sK8sClusterIdNodepoolsNodepoolIdDelete",
		strings.ToUpper("Delete"),
		"/cloudapi/v5/k8s/{k8sClusterId}/nodepools/{nodepoolId}",
		K8sK8sClusterIdNodepoolsNodepoolIdDelete,
	},

	Route{
		"K8sK8sClusterIdNodepoolsNodepoolIdGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/k8s/{k8sClusterId}/nodepools/{nodepoolId}",
		K8sK8sClusterIdNodepoolsNodepoolIdGet,
	},

	Route{
		"K8sK8sClusterIdNodepoolsNodepoolIdNodesGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/k8s/{k8sClusterId}/nodepools/{nodepoolId}/nodes",
		K8sK8sClusterIdNodepoolsNodepoolIdNodesGet,
	},

	Route{
		"K8sK8sClusterIdNodepoolsNodepoolIdNodesNodeIdGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/k8s/{k8sClusterId}/nodepools/{nodepoolId}/nodes/{nodeId}",
		K8sK8sClusterIdNodepoolsNodepoolIdNodesNodeIdGet,
	},

	Route{
		"K8sK8sClusterIdNodepoolsNodepoolIdNodesNodeIdReplacePost",
		strings.ToUpper("Post"),
		"/cloudapi/v5/k8s/{k8sClusterId}/nodepools/{nodepoolId}/nodes/{nodeId}/replace",
		K8sK8sClusterIdNodepoolsNodepoolIdNodesNodeIdReplacePost,
	},

	Route{
		"K8sK8sClusterIdNodepoolsNodepoolIdPut",
		strings.ToUpper("Put"),
		"/cloudapi/v5/k8s/{k8sClusterId}/nodepools/{nodepoolId}",
		K8sK8sClusterIdNodepoolsNodepoolIdPut,
	},

	Route{
		"K8sK8sClusterIdNodepoolsPost",
		strings.ToUpper("Post"),
		"/cloudapi/v5/k8s/{k8sClusterId}/nodepools",
		K8sK8sClusterIdNodepoolsPost,
	},

	Route{
		"K8sK8sClusterIdPut",
		strings.ToUpper("Put"),
		"/cloudapi/v5/k8s/{k8sClusterId}",
		K8sK8sClusterIdPut,
	},

	Route{
		"K8sPost",
		strings.ToUpper("Post"),
		"/cloudapi/v5/k8s",
		K8sPost,
	},

	Route{
		"K8sVersionsClusterVersionCompatibilitiesGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/k8s/versions/{clusterVersion}/compatibilities",
		K8sVersionsClusterVersionCompatibilitiesGet,
	},

	Route{
		"K8sVersionsDefaultGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/k8s/versions/default",
		K8sVersionsDefaultGet,
	},

	Route{
		"K8sVersionsGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/k8s/versions",
		K8sVersionsGet,
	},

	Route{
		"DatacentersDatacenterIdLabelsGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/datacenters/{datacenterId}/labels",
		DatacentersDatacenterIdLabelsGet,
	},

	Route{
		"DatacentersDatacenterIdLabelsKeyDelete",
		strings.ToUpper("Delete"),
		"/cloudapi/v5/datacenters/{datacenterId}/labels/{key}",
		DatacentersDatacenterIdLabelsKeyDelete,
	},

	Route{
		"DatacentersDatacenterIdLabelsKeyGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/datacenters/{datacenterId}/labels/{key}",
		DatacentersDatacenterIdLabelsKeyGet,
	},

	Route{
		"DatacentersDatacenterIdLabelsKeyPut",
		strings.ToUpper("Put"),
		"/cloudapi/v5/datacenters/{datacenterId}/labels/{key}",
		DatacentersDatacenterIdLabelsKeyPut,
	},

	Route{
		"DatacentersDatacenterIdLabelsPost",
		strings.ToUpper("Post"),
		"/cloudapi/v5/datacenters/{datacenterId}/labels",
		DatacentersDatacenterIdLabelsPost,
	},

	Route{
		"DatacentersDatacenterIdServersServerIdLabelsGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/datacenters/{datacenterId}/servers/{serverId}/labels",
		DatacentersDatacenterIdServersServerIdLabelsGet,
	},

	Route{
		"DatacentersDatacenterIdServersServerIdLabelsKeyDelete",
		strings.ToUpper("Delete"),
		"/cloudapi/v5/datacenters/{datacenterId}/servers/{serverId}/labels/{key}",
		DatacentersDatacenterIdServersServerIdLabelsKeyDelete,
	},

	Route{
		"DatacentersDatacenterIdServersServerIdLabelsKeyGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/datacenters/{datacenterId}/servers/{serverId}/labels/{key}",
		DatacentersDatacenterIdServersServerIdLabelsKeyGet,
	},

	Route{
		"DatacentersDatacenterIdServersServerIdLabelsKeyPut",
		strings.ToUpper("Put"),
		"/cloudapi/v5/datacenters/{datacenterId}/servers/{serverId}/labels/{key}",
		DatacentersDatacenterIdServersServerIdLabelsKeyPut,
	},

	Route{
		"DatacentersDatacenterIdServersServerIdLabelsPost",
		strings.ToUpper("Post"),
		"/cloudapi/v5/datacenters/{datacenterId}/servers/{serverId}/labels",
		DatacentersDatacenterIdServersServerIdLabelsPost,
	},

	Route{
		"DatacentersDatacenterIdVolumesVolumeIdLabelsGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/datacenters/{datacenterId}/volumes/{volumeId}/labels",
		DatacentersDatacenterIdVolumesVolumeIdLabelsGet,
	},

	Route{
		"DatacentersDatacenterIdVolumesVolumeIdLabelsKeyDelete",
		strings.ToUpper("Delete"),
		"/cloudapi/v5/datacenters/{datacenterId}/volumes/{volumeId}/labels/{key}",
		DatacentersDatacenterIdVolumesVolumeIdLabelsKeyDelete,
	},

	Route{
		"DatacentersDatacenterIdVolumesVolumeIdLabelsKeyGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/datacenters/{datacenterId}/volumes/{volumeId}/labels/{key}",
		DatacentersDatacenterIdVolumesVolumeIdLabelsKeyGet,
	},

	Route{
		"DatacentersDatacenterIdVolumesVolumeIdLabelsKeyPut",
		strings.ToUpper("Put"),
		"/cloudapi/v5/datacenters/{datacenterId}/volumes/{volumeId}/labels/{key}",
		DatacentersDatacenterIdVolumesVolumeIdLabelsKeyPut,
	},

	Route{
		"DatacentersDatacenterIdVolumesVolumeIdLabelsPost",
		strings.ToUpper("Post"),
		"/cloudapi/v5/datacenters/{datacenterId}/volumes/{volumeId}/labels",
		DatacentersDatacenterIdVolumesVolumeIdLabelsPost,
	},

	Route{
		"IpblocksIpblockIdLabelsGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/ipblocks/{ipblockId}/labels",
		IpblocksIpblockIdLabelsGet,
	},

	Route{
		"IpblocksIpblockIdLabelsKeyDelete",
		strings.ToUpper("Delete"),
		"/cloudapi/v5/ipblocks/{ipblockId}/labels/{key}",
		IpblocksIpblockIdLabelsKeyDelete,
	},

	Route{
		"IpblocksIpblockIdLabelsKeyGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/ipblocks/{ipblockId}/labels/{key}",
		IpblocksIpblockIdLabelsKeyGet,
	},

	Route{
		"IpblocksIpblockIdLabelsKeyPut",
		strings.ToUpper("Put"),
		"/cloudapi/v5/ipblocks/{ipblockId}/labels/{key}",
		IpblocksIpblockIdLabelsKeyPut,
	},

	Route{
		"IpblocksIpblockIdLabelsPost",
		strings.ToUpper("Post"),
		"/cloudapi/v5/ipblocks/{ipblockId}/labels",
		IpblocksIpblockIdLabelsPost,
	},

	Route{
		"LabelsGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/labels",
		LabelsGet,
	},

	Route{
		"LabelsLabelurnGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/labels/{labelurn}",
		LabelsLabelurnGet,
	},

	Route{
		"SnapshotsSnapshotIdLabelsGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/snapshots/{snapshotId}/labels",
		SnapshotsSnapshotIdLabelsGet,
	},

	Route{
		"SnapshotsSnapshotIdLabelsKeyDelete",
		strings.ToUpper("Delete"),
		"/cloudapi/v5/snapshots/{snapshotId}/labels/{key}",
		SnapshotsSnapshotIdLabelsKeyDelete,
	},

	Route{
		"SnapshotsSnapshotIdLabelsKeyGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/snapshots/{snapshotId}/labels/{key}",
		SnapshotsSnapshotIdLabelsKeyGet,
	},

	Route{
		"SnapshotsSnapshotIdLabelsKeyPut",
		strings.ToUpper("Put"),
		"/cloudapi/v5/snapshots/{snapshotId}/labels/{key}",
		SnapshotsSnapshotIdLabelsKeyPut,
	},

	Route{
		"SnapshotsSnapshotIdLabelsPost",
		strings.ToUpper("Post"),
		"/cloudapi/v5/snapshots/{snapshotId}/labels",
		SnapshotsSnapshotIdLabelsPost,
	},

	Route{
		"DatacentersDatacenterIdLansGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/datacenters/{datacenterId}/lans",
		DatacentersDatacenterIdLansGet,
	},

	Route{
		"DatacentersDatacenterIdLansLanIdDelete",
		strings.ToUpper("Delete"),
		"/cloudapi/v5/datacenters/{datacenterId}/lans/{lanId}",
		DatacentersDatacenterIdLansLanIdDelete,
	},

	Route{
		"DatacentersDatacenterIdLansLanIdGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/datacenters/{datacenterId}/lans/{lanId}",
		DatacentersDatacenterIdLansLanIdGet,
	},

	Route{
		"DatacentersDatacenterIdLansLanIdNicsGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/datacenters/{datacenterId}/lans/{lanId}/nics",
		DatacentersDatacenterIdLansLanIdNicsGet,
	},

	Route{
		"DatacentersDatacenterIdLansLanIdNicsNicIdGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/datacenters/{datacenterId}/lans/{lanId}/nics/{nicId}",
		DatacentersDatacenterIdLansLanIdNicsNicIdGet,
	},

	Route{
		"DatacentersDatacenterIdLansLanIdNicsPost",
		strings.ToUpper("Post"),
		"/cloudapi/v5/datacenters/{datacenterId}/lans/{lanId}/nics",
		DatacentersDatacenterIdLansLanIdNicsPost,
	},

	Route{
		"DatacentersDatacenterIdLansLanIdPatch",
		strings.ToUpper("Patch"),
		"/cloudapi/v5/datacenters/{datacenterId}/lans/{lanId}",
		DatacentersDatacenterIdLansLanIdPatch,
	},

	Route{
		"DatacentersDatacenterIdLansLanIdPut",
		strings.ToUpper("Put"),
		"/cloudapi/v5/datacenters/{datacenterId}/lans/{lanId}",
		DatacentersDatacenterIdLansLanIdPut,
	},

	Route{
		"DatacentersDatacenterIdLansPost",
		strings.ToUpper("Post"),
		"/cloudapi/v5/datacenters/{datacenterId}/lans",
		DatacentersDatacenterIdLansPost,
	},

	Route{
		"DatacentersDatacenterIdLoadbalancersGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/datacenters/{datacenterId}/loadbalancers",
		DatacentersDatacenterIdLoadbalancersGet,
	},

	Route{
		"DatacentersDatacenterIdLoadbalancersLoadbalancerIdBalancednicsGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/datacenters/{datacenterId}/loadbalancers/{loadbalancerId}/balancednics",
		DatacentersDatacenterIdLoadbalancersLoadbalancerIdBalancednicsGet,
	},

	Route{
		"DatacentersDatacenterIdLoadbalancersLoadbalancerIdBalancednicsNicIdDelete",
		strings.ToUpper("Delete"),
		"/cloudapi/v5/datacenters/{datacenterId}/loadbalancers/{loadbalancerId}/balancednics/{nicId}",
		DatacentersDatacenterIdLoadbalancersLoadbalancerIdBalancednicsNicIdDelete,
	},

	Route{
		"DatacentersDatacenterIdLoadbalancersLoadbalancerIdBalancednicsNicIdGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/datacenters/{datacenterId}/loadbalancers/{loadbalancerId}/balancednics/{nicId}",
		DatacentersDatacenterIdLoadbalancersLoadbalancerIdBalancednicsNicIdGet,
	},

	Route{
		"DatacentersDatacenterIdLoadbalancersLoadbalancerIdBalancednicsPost",
		strings.ToUpper("Post"),
		"/cloudapi/v5/datacenters/{datacenterId}/loadbalancers/{loadbalancerId}/balancednics",
		DatacentersDatacenterIdLoadbalancersLoadbalancerIdBalancednicsPost,
	},

	Route{
		"DatacentersDatacenterIdLoadbalancersLoadbalancerIdDelete",
		strings.ToUpper("Delete"),
		"/cloudapi/v5/datacenters/{datacenterId}/loadbalancers/{loadbalancerId}",
		DatacentersDatacenterIdLoadbalancersLoadbalancerIdDelete,
	},

	Route{
		"DatacentersDatacenterIdLoadbalancersLoadbalancerIdGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/datacenters/{datacenterId}/loadbalancers/{loadbalancerId}",
		DatacentersDatacenterIdLoadbalancersLoadbalancerIdGet,
	},

	Route{
		"DatacentersDatacenterIdLoadbalancersLoadbalancerIdPatch",
		strings.ToUpper("Patch"),
		"/cloudapi/v5/datacenters/{datacenterId}/loadbalancers/{loadbalancerId}",
		DatacentersDatacenterIdLoadbalancersLoadbalancerIdPatch,
	},

	Route{
		"DatacentersDatacenterIdLoadbalancersLoadbalancerIdPut",
		strings.ToUpper("Put"),
		"/cloudapi/v5/datacenters/{datacenterId}/loadbalancers/{loadbalancerId}",
		DatacentersDatacenterIdLoadbalancersLoadbalancerIdPut,
	},

	Route{
		"DatacentersDatacenterIdLoadbalancersPost",
		strings.ToUpper("Post"),
		"/cloudapi/v5/datacenters/{datacenterId}/loadbalancers",
		DatacentersDatacenterIdLoadbalancersPost,
	},

	Route{
		"LocationsGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/locations",
		LocationsGet,
	},

	Route{
		"LocationsRegionIdGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/locations/{regionId}",
		LocationsRegionIdGet,
	},

	Route{
		"LocationsRegionIdLocationIdGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/locations/{regionId}/{locationId}",
		LocationsRegionIdLocationIdGet,
	},

	Route{
		"DatacentersDatacenterIdServersServerIdNicsGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/datacenters/{datacenterId}/servers/{serverId}/nics",
		DatacentersDatacenterIdServersServerIdNicsGet,
	},

	Route{
		"DatacentersDatacenterIdServersServerIdNicsNicIdDelete",
		strings.ToUpper("Delete"),
		"/cloudapi/v5/datacenters/{datacenterId}/servers/{serverId}/nics/{nicId}",
		DatacentersDatacenterIdServersServerIdNicsNicIdDelete,
	},

	Route{
		"DatacentersDatacenterIdServersServerIdNicsNicIdFirewallrulesFirewallruleIdDelete",
		strings.ToUpper("Delete"),
		"/cloudapi/v5/datacenters/{datacenterId}/servers/{serverId}/nics/{nicId}/firewallrules/{firewallruleId}",
		DatacentersDatacenterIdServersServerIdNicsNicIdFirewallrulesFirewallruleIdDelete,
	},

	Route{
		"DatacentersDatacenterIdServersServerIdNicsNicIdFirewallrulesFirewallruleIdGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/datacenters/{datacenterId}/servers/{serverId}/nics/{nicId}/firewallrules/{firewallruleId}",
		DatacentersDatacenterIdServersServerIdNicsNicIdFirewallrulesFirewallruleIdGet,
	},

	Route{
		"DatacentersDatacenterIdServersServerIdNicsNicIdFirewallrulesFirewallruleIdPatch",
		strings.ToUpper("Patch"),
		"/cloudapi/v5/datacenters/{datacenterId}/servers/{serverId}/nics/{nicId}/firewallrules/{firewallruleId}",
		DatacentersDatacenterIdServersServerIdNicsNicIdFirewallrulesFirewallruleIdPatch,
	},

	Route{
		"DatacentersDatacenterIdServersServerIdNicsNicIdFirewallrulesFirewallruleIdPut",
		strings.ToUpper("Put"),
		"/cloudapi/v5/datacenters/{datacenterId}/servers/{serverId}/nics/{nicId}/firewallrules/{firewallruleId}",
		DatacentersDatacenterIdServersServerIdNicsNicIdFirewallrulesFirewallruleIdPut,
	},

	Route{
		"DatacentersDatacenterIdServersServerIdNicsNicIdFirewallrulesGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/datacenters/{datacenterId}/servers/{serverId}/nics/{nicId}/firewallrules",
		DatacentersDatacenterIdServersServerIdNicsNicIdFirewallrulesGet,
	},

	Route{
		"DatacentersDatacenterIdServersServerIdNicsNicIdFirewallrulesPost",
		strings.ToUpper("Post"),
		"/cloudapi/v5/datacenters/{datacenterId}/servers/{serverId}/nics/{nicId}/firewallrules",
		DatacentersDatacenterIdServersServerIdNicsNicIdFirewallrulesPost,
	},

	Route{
		"DatacentersDatacenterIdServersServerIdNicsNicIdGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/datacenters/{datacenterId}/servers/{serverId}/nics/{nicId}",
		DatacentersDatacenterIdServersServerIdNicsNicIdGet,
	},

	Route{
		"DatacentersDatacenterIdServersServerIdNicsNicIdPatch",
		strings.ToUpper("Patch"),
		"/cloudapi/v5/datacenters/{datacenterId}/servers/{serverId}/nics/{nicId}",
		DatacentersDatacenterIdServersServerIdNicsNicIdPatch,
	},

	Route{
		"DatacentersDatacenterIdServersServerIdNicsNicIdPut",
		strings.ToUpper("Put"),
		"/cloudapi/v5/datacenters/{datacenterId}/servers/{serverId}/nics/{nicId}",
		DatacentersDatacenterIdServersServerIdNicsNicIdPut,
	},

	Route{
		"DatacentersDatacenterIdServersServerIdNicsPost",
		strings.ToUpper("Post"),
		"/cloudapi/v5/datacenters/{datacenterId}/servers/{serverId}/nics",
		DatacentersDatacenterIdServersServerIdNicsPost,
	},

	Route{
		"PccsGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/pccs",
		PccsGet,
	},

	Route{
		"PccsPccIdDelete",
		strings.ToUpper("Delete"),
		"/cloudapi/v5/pccs/{pccId}",
		PccsPccIdDelete,
	},

	Route{
		"PccsPccIdGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/pccs/{pccId}",
		PccsPccIdGet,
	},

	Route{
		"PccsPccIdPatch",
		strings.ToUpper("Patch"),
		"/cloudapi/v5/pccs/{pccId}",
		PccsPccIdPatch,
	},

	Route{
		"PccsPost",
		strings.ToUpper("Post"),
		"/cloudapi/v5/pccs",
		PccsPost,
	},

	Route{
		"RequestsGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/requests",
		RequestsGet,
	},

	Route{
		"RequestsRequestIdGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/requests/{requestId}",
		RequestsRequestIdGet,
	},

	Route{
		"RequestsRequestIdStatusGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/requests/{requestId}/status",
		RequestsRequestIdStatusGet,
	},

	Route{
		"DatacentersDatacenterIdServersGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/datacenters/{datacenterId}/servers",
		DatacentersDatacenterIdServersGet,
	},

	Route{
		"DatacentersDatacenterIdServersPost",
		strings.ToUpper("Post"),
		"/cloudapi/v5/datacenters/{datacenterId}/servers",
		DatacentersDatacenterIdServersPost,
	},

	Route{
		"DatacentersDatacenterIdServersServerIdCdromsCdromIdDelete",
		strings.ToUpper("Delete"),
		"/cloudapi/v5/datacenters/{datacenterId}/servers/{serverId}/cdroms/{cdromId}",
		DatacentersDatacenterIdServersServerIdCdromsCdromIdDelete,
	},

	Route{
		"DatacentersDatacenterIdServersServerIdCdromsCdromIdGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/datacenters/{datacenterId}/servers/{serverId}/cdroms/{cdromId}",
		DatacentersDatacenterIdServersServerIdCdromsCdromIdGet,
	},

	Route{
		"DatacentersDatacenterIdServersServerIdCdromsGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/datacenters/{datacenterId}/servers/{serverId}/cdroms",
		DatacentersDatacenterIdServersServerIdCdromsGet,
	},

	Route{
		"DatacentersDatacenterIdServersServerIdCdromsPost",
		strings.ToUpper("Post"),
		"/cloudapi/v5/datacenters/{datacenterId}/servers/{serverId}/cdroms",
		DatacentersDatacenterIdServersServerIdCdromsPost,
	},

	Route{
		"DatacentersDatacenterIdServersServerIdDelete",
		strings.ToUpper("Delete"),
		"/cloudapi/v5/datacenters/{datacenterId}/servers/{serverId}",
		DatacentersDatacenterIdServersServerIdDelete,
	},

	Route{
		"DatacentersDatacenterIdServersServerIdGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/datacenters/{datacenterId}/servers/{serverId}",
		DatacentersDatacenterIdServersServerIdGet,
	},

	Route{
		"DatacentersDatacenterIdServersServerIdPatch",
		strings.ToUpper("Patch"),
		"/cloudapi/v5/datacenters/{datacenterId}/servers/{serverId}",
		DatacentersDatacenterIdServersServerIdPatch,
	},

	Route{
		"DatacentersDatacenterIdServersServerIdPut",
		strings.ToUpper("Put"),
		"/cloudapi/v5/datacenters/{datacenterId}/servers/{serverId}",
		DatacentersDatacenterIdServersServerIdPut,
	},

	Route{
		"DatacentersDatacenterIdServersServerIdRebootPost",
		strings.ToUpper("Post"),
		"/cloudapi/v5/datacenters/{datacenterId}/servers/{serverId}/reboot",
		DatacentersDatacenterIdServersServerIdRebootPost,
	},

	Route{
		"DatacentersDatacenterIdServersServerIdStartPost",
		strings.ToUpper("Post"),
		"/cloudapi/v5/datacenters/{datacenterId}/servers/{serverId}/start",
		DatacentersDatacenterIdServersServerIdStartPost,
	},

	Route{
		"DatacentersDatacenterIdServersServerIdStopPost",
		strings.ToUpper("Post"),
		"/cloudapi/v5/datacenters/{datacenterId}/servers/{serverId}/stop",
		DatacentersDatacenterIdServersServerIdStopPost,
	},

	Route{
		"DatacentersDatacenterIdServersServerIdUpgradePost",
		strings.ToUpper("Post"),
		"/cloudapi/v5/datacenters/{datacenterId}/servers/{serverId}/upgrade",
		DatacentersDatacenterIdServersServerIdUpgradePost,
	},

	Route{
		"DatacentersDatacenterIdServersServerIdVolumesGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/datacenters/{datacenterId}/servers/{serverId}/volumes",
		DatacentersDatacenterIdServersServerIdVolumesGet,
	},

	Route{
		"DatacentersDatacenterIdServersServerIdVolumesPost",
		strings.ToUpper("Post"),
		"/cloudapi/v5/datacenters/{datacenterId}/servers/{serverId}/volumes",
		DatacentersDatacenterIdServersServerIdVolumesPost,
	},

	Route{
		"DatacentersDatacenterIdServersServerIdVolumesVolumeIdDelete",
		strings.ToUpper("Delete"),
		"/cloudapi/v5/datacenters/{datacenterId}/servers/{serverId}/volumes/{volumeId}",
		DatacentersDatacenterIdServersServerIdVolumesVolumeIdDelete,
	},

	Route{
		"DatacentersDatacenterIdServersServerIdVolumesVolumeIdGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/datacenters/{datacenterId}/servers/{serverId}/volumes/{volumeId}",
		DatacentersDatacenterIdServersServerIdVolumesVolumeIdGet,
	},

	Route{
		"SnapshotsGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/snapshots",
		SnapshotsGet,
	},

	Route{
		"SnapshotsSnapshotIdDelete",
		strings.ToUpper("Delete"),
		"/cloudapi/v5/snapshots/{snapshotId}",
		SnapshotsSnapshotIdDelete,
	},

	Route{
		"SnapshotsSnapshotIdGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/snapshots/{snapshotId}",
		SnapshotsSnapshotIdGet,
	},

	Route{
		"SnapshotsSnapshotIdPatch",
		strings.ToUpper("Patch"),
		"/cloudapi/v5/snapshots/{snapshotId}",
		SnapshotsSnapshotIdPatch,
	},

	Route{
		"SnapshotsSnapshotIdPut",
		strings.ToUpper("Put"),
		"/cloudapi/v5/snapshots/{snapshotId}",
		SnapshotsSnapshotIdPut,
	},

	Route{
		"UmGroupsGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/um/groups",
		UmGroupsGet,
	},

	Route{
		"UmGroupsGroupIdDelete",
		strings.ToUpper("Delete"),
		"/cloudapi/v5/um/groups/{groupId}",
		UmGroupsGroupIdDelete,
	},

	Route{
		"UmGroupsGroupIdGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/um/groups/{groupId}",
		UmGroupsGroupIdGet,
	},

	Route{
		"UmGroupsGroupIdPut",
		strings.ToUpper("Put"),
		"/cloudapi/v5/um/groups/{groupId}",
		UmGroupsGroupIdPut,
	},

	Route{
		"UmGroupsGroupIdResourcesGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/um/groups/{groupId}/resources",
		UmGroupsGroupIdResourcesGet,
	},

	Route{
		"UmGroupsGroupIdSharesGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/um/groups/{groupId}/shares",
		UmGroupsGroupIdSharesGet,
	},

	Route{
		"UmGroupsGroupIdSharesResourceIdDelete",
		strings.ToUpper("Delete"),
		"/cloudapi/v5/um/groups/{groupId}/shares/{resourceId}",
		UmGroupsGroupIdSharesResourceIdDelete,
	},

	Route{
		"UmGroupsGroupIdSharesResourceIdGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/um/groups/{groupId}/shares/{resourceId}",
		UmGroupsGroupIdSharesResourceIdGet,
	},

	Route{
		"UmGroupsGroupIdSharesResourceIdPost",
		strings.ToUpper("Post"),
		"/cloudapi/v5/um/groups/{groupId}/shares/{resourceId}",
		UmGroupsGroupIdSharesResourceIdPost,
	},

	Route{
		"UmGroupsGroupIdSharesResourceIdPut",
		strings.ToUpper("Put"),
		"/cloudapi/v5/um/groups/{groupId}/shares/{resourceId}",
		UmGroupsGroupIdSharesResourceIdPut,
	},

	Route{
		"UmGroupsGroupIdUsersGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/um/groups/{groupId}/users",
		UmGroupsGroupIdUsersGet,
	},

	Route{
		"UmGroupsGroupIdUsersPost",
		strings.ToUpper("Post"),
		"/cloudapi/v5/um/groups/{groupId}/users",
		UmGroupsGroupIdUsersPost,
	},

	Route{
		"UmGroupsGroupIdUsersUserIdDelete",
		strings.ToUpper("Delete"),
		"/cloudapi/v5/um/groups/{groupId}/users/{userId}",
		UmGroupsGroupIdUsersUserIdDelete,
	},

	Route{
		"UmGroupsPost",
		strings.ToUpper("Post"),
		"/cloudapi/v5/um/groups",
		UmGroupsPost,
	},

	Route{
		"UmResourcesGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/um/resources",
		UmResourcesGet,
	},

	Route{
		"UmResourcesResourceTypeGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/um/resources/{resourceType}",
		UmResourcesResourceTypeGet,
	},

	Route{
		"UmResourcesResourceTypeResourceIdGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/um/resources/{resourceType}/{resourceId}",
		UmResourcesResourceTypeResourceIdGet,
	},

	Route{
		"UmUsersGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/um/users",
		UmUsersGet,
	},

	Route{
		"UmUsersPost",
		strings.ToUpper("Post"),
		"/cloudapi/v5/um/users",
		UmUsersPost,
	},

	Route{
		"UmUsersUserIdDelete",
		strings.ToUpper("Delete"),
		"/cloudapi/v5/um/users/{userId}",
		UmUsersUserIdDelete,
	},

	Route{
		"UmUsersUserIdGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/um/users/{userId}",
		UmUsersUserIdGet,
	},

	Route{
		"UmUsersUserIdGroupsGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/um/users/{userId}/groups",
		UmUsersUserIdGroupsGet,
	},

	Route{
		"UmUsersUserIdOwnsGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/um/users/{userId}/owns",
		UmUsersUserIdOwnsGet,
	},

	Route{
		"UmUsersUserIdPut",
		strings.ToUpper("Put"),
		"/cloudapi/v5/um/users/{userId}",
		UmUsersUserIdPut,
	},

	Route{
		"UmUsersUserIdS3keysGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/um/users/{userId}/s3keys",
		UmUsersUserIdS3keysGet,
	},

	Route{
		"UmUsersUserIdS3keysKeyIdDelete",
		strings.ToUpper("Delete"),
		"/cloudapi/v5/um/users/{userId}/s3keys/{keyId}",
		UmUsersUserIdS3keysKeyIdDelete,
	},

	Route{
		"UmUsersUserIdS3keysKeyIdGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/um/users/{userId}/s3keys/{keyId}",
		UmUsersUserIdS3keysKeyIdGet,
	},

	Route{
		"UmUsersUserIdS3keysKeyIdPut",
		strings.ToUpper("Put"),
		"/cloudapi/v5/um/users/{userId}/s3keys/{keyId}",
		UmUsersUserIdS3keysKeyIdPut,
	},

	Route{
		"UmUsersUserIdS3keysPost",
		strings.ToUpper("Post"),
		"/cloudapi/v5/um/users/{userId}/s3keys",
		UmUsersUserIdS3keysPost,
	},

	Route{
		"UmUsersUserIdS3ssourlGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/um/users/{userId}/s3ssourl",
		UmUsersUserIdS3ssourlGet,
	},

	Route{
		"DatacentersDatacenterIdVolumesGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/datacenters/{datacenterId}/volumes",
		DatacentersDatacenterIdVolumesGet,
	},

	Route{
		"DatacentersDatacenterIdVolumesPost",
		strings.ToUpper("Post"),
		"/cloudapi/v5/datacenters/{datacenterId}/volumes",
		DatacentersDatacenterIdVolumesPost,
	},

	Route{
		"DatacentersDatacenterIdVolumesVolumeIdCreateSnapshotPost",
		strings.ToUpper("Post"),
		"/cloudapi/v5/datacenters/{datacenterId}/volumes/{volumeId}/create-snapshot",
		DatacentersDatacenterIdVolumesVolumeIdCreateSnapshotPost,
	},

	Route{
		"DatacentersDatacenterIdVolumesVolumeIdDelete",
		strings.ToUpper("Delete"),
		"/cloudapi/v5/datacenters/{datacenterId}/volumes/{volumeId}",
		DatacentersDatacenterIdVolumesVolumeIdDelete,
	},

	Route{
		"DatacentersDatacenterIdVolumesVolumeIdGet",
		strings.ToUpper("Get"),
		"/cloudapi/v5/datacenters/{datacenterId}/volumes/{volumeId}",
		DatacentersDatacenterIdVolumesVolumeIdGet,
	},

	Route{
		"DatacentersDatacenterIdVolumesVolumeIdPatch",
		strings.ToUpper("Patch"),
		"/cloudapi/v5/datacenters/{datacenterId}/volumes/{volumeId}",
		DatacentersDatacenterIdVolumesVolumeIdPatch,
	},

	Route{
		"DatacentersDatacenterIdVolumesVolumeIdPut",
		strings.ToUpper("Put"),
		"/cloudapi/v5/datacenters/{datacenterId}/volumes/{volumeId}",
		DatacentersDatacenterIdVolumesVolumeIdPut,
	},

	Route{
		"DatacentersDatacenterIdVolumesVolumeIdRestoreSnapshotPost",
		strings.ToUpper("Post"),
		"/cloudapi/v5/datacenters/{datacenterId}/volumes/{volumeId}/restore-snapshot",
		DatacentersDatacenterIdVolumesVolumeIdRestoreSnapshotPost,
	},
}
